# Generated by Django 3.2.7 on 2022-02-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='currency',
            field=models.CharField(blank=True, default='TMT - Turkmenistani Manat', max_length=255, null=True),
        ),
    ]
